[package]
name = "hashcmp"
version = "0.1.0"
authors = ["Robin Kautz <mail@bob3000.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
anyhow = "1.0.37"
md-5 = "0.9.1"
